[codestyle]
workspace_dir='.'
template_file='./template.cpp'
lang='cpp'

[compiler]
compile_command='/opt/homebrew/bin/g++-12 main.cpp -o main -ld_classic -std=c++20'
compile_only_when_diff_detected=true

[tester]
compile_before_testing=true
compile_only_when_diff_detected=true