[codestyle]
workspace_dir='.'
template_file='./template.cpp'
lang='cpp'

[compiler]
compile_command='/opt/homebrew/bin/g++-12 -fdiagnostics-color=always main.cpp -o main -ld_classic -gdwarf-3 -std=c++20 -DHASSAKU_DEBUG'
compile_only_when_diff_detected=true

[tester]
compile_before_testing=true
compile_only_when_diff_detected=true